// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkeqVcHRa0lHF4IM15tAWUAm7gsGRAe78',
    appId: '1:798717939681:web:feed02fba2a7f6e96e4ca0',
    messagingSenderId: '798717939681',
    projectId: 'medremind-373b6',
    authDomain: 'medremind-373b6.firebaseapp.com',
    storageBucket: 'medremind-373b6.firebasestorage.app',
    measurementId: 'G-JMMWZ62TST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwroqsLpeZcj7Kt5sL-0zCYEyN-hAQ8fA',
    appId: '1:798717939681:android:f75d541eaf11e8096e4ca0',
    messagingSenderId: '798717939681',
    projectId: 'medremind-373b6',
    storageBucket: 'medremind-373b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqzB1iKgcECi_ut8sAwJddhFtsLmKaiAk',
    appId: '1:798717939681:ios:3badd28c2153c1996e4ca0',
    messagingSenderId: '798717939681',
    projectId: 'medremind-373b6',
    storageBucket: 'medremind-373b6.firebasestorage.app',
    iosClientId: '798717939681-p16b0tgifl7k9akin3r7mjghmbvhahqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.medRemindV2',
  );
}
